### ISSUE TITLE
Default extension for HDF files

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/DESCFormats#1]
@joezuntz  I'm not sure what the official standard is, but `astropy` gets very confused when asked to handle `.hdf` files instead of `.hdf5`. Would it be ok to update the file extension for HDF files to `.hdf5` ?

https://github.com/LSSTDESC/DESCFormats/blob/da0a60d608132ffc8afce56f37a7361e345bc4b9/descformats/base.py#L55

**Comment by joezuntz** [comment]
Yes, that's fine.  Thanks!

**Comment by joezuntz** [comment]
I've modified this now - cheers.
Joe
